EXTRAFLAGS        += -flto

TAP_DANCE_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
RGBLIGHT_ENABLE = yes
CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMMAND_ENABLE   = no
SWAP_HANDS_ENABLE= no
SPACE_CADET_ENABLE = no

KEYLOGGER_ENABLE = yes
AUTOLOG_ENABLE ?= yes

ifeq (${AUTOLOG_ENABLE},yes)
KEYLOGGER_ENABLE = yes
OPT_DEFS += -DAUTOLOG_ENABLE
endif

ifeq (${KEYLOGGER_ENABLE},yes)
OPT_DEFS += -DKEYLOGGER_ENABLE
CONSOLE_ENABLE = yes
endif

OPT_DEFS += -DUSER_PRINT
